I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 669, in script call
    call display(Race.Black)
  File "game/script.rpy", line 671, in script call
    call display(Race.Hispanic)
  File "game/script.rpy", line 667, in script call
    call display(Race.Asian)
  File "game/script.rpy", line 671, in script call
    call display(Race.Hispanic)
  File "game/script.rpy", line 678, in script
    python:
  File "game/script.rpy", line 680, in <module>
    male_salary = round(base_salary * RaceBiases[race][Gender.Man], 2)
KeyError: None

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 669, in script call
    call display(Race.Black)
  File "game/script.rpy", line 671, in script call
    call display(Race.Hispanic)
  File "game/script.rpy", line 667, in script call
    call display(Race.Asian)
  File "game/script.rpy", line 671, in script call
    call display(Race.Hispanic)
  File "game/script.rpy", line 678, in script
    python:
  File "/Users/Arnav1/Documents/renpy-8.0.3-sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/Arnav1/Documents/renpy-8.0.3-sdk/renpy/python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 680, in <module>
    male_salary = round(base_salary * RaceBiases[race][Gender.Man], 2)
KeyError: None

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
CS492_Project 1.0
Mon Apr 10 03:25:12 2023
